### ISSUE TITLE
No role in the database

### ISSUE THREAD

**Issue by dedioweb** [msgphp/msgphp#265] opened 2019-01-15 11:14 UTC
Hi, 
the registration of a user works well, however, no role is associated with the user.
**schema database :** 
![database-user](https://user-images.githubusercontent.com/20359968/51176846-4dd26e00-18be-11e9-9c7d-4ff9a2540214.png)

**config/package/mssphp_user.make.php** 

`<?php

// generated by `make:user:msgphp`
// this configuration may be merged into your existing application configuration

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use function Symfony\Component\DependencyInjection\Loader\Configurator\ref;

return function (ContainerConfigurator $container) {
    $container->extension('msgphp_user', array (
  'class_mapping' => 
  array (
    'MsgPhp\\User\\Entity\\Role' => 'App\\Entity\\User\\Role',
    'MsgPhp\\User\\Entity\\UserRole' => 'App\\Entity\\User\\UserRole',
  ),
  'role_providers' => 
  array (
    'default' => 
    array (
      0 => 'ROLE_USER',
    ),
    0 => 'MsgPhp\\User\\Role\\UserRoleProvider',
  ),
));

    $container->services()
        ->defaults()
            ->private()
            ->autoconfigure()
            ->autowire()

        ->set(App\Console\ClassContextElementFactory::class)
        ->alias(MsgPhp\Domain\Infra\Console\Context\ClassContextElementFactoryInterface::class, App\Console\ClassContextElementFactory::class)
    ;
};
`

thank you for your reply

**Comment by ro0NL** [comment] 2019-01-15 11:41
Hi @dedioweb 

That's by design :) but undocumented still.

```yaml
msgphp_user:
  role_providers:
    - default: [ROLE_USER]
    - MsgPhp\User\Role\UserRoleProvider # service ID
```

This means each authenticated _domain user_ will get a ROLE_USER in the session (the security user DTO) by default.

By adding the `UserRoleProvider` service, each  **database role** assigned to the authenicated _domain users_ will be available from the security user as well.

To add a (specific) database role to a (specific)  user, you can use: `$ bin/console user:role:add`

Or programmatic:  `$bus->disaptch(new AddUserRoleComand($userId, 'ROLE_SOME_DB_ROLE'));`, which you can dispatch right after `CreateUserCommand`.

hope it clarifies :)

**Comment by dedioweb** [comment] 2019-01-15 12:16
ok @ro0NL 
if I understand,
I must add
`$bus->disaptch(new AddUserRoleComand($userId, 'ROLE_SOME_DB_ROLE'));`
in the RegisterController inside `if ($ form-> isSubmitted () && $ form-> isValid ()) {`

That I replace the 'ROLE_SOME_DB_ROLE' by the name present in the ROLE table?

**Comment by ro0NL** [comment] 2019-01-15 12:31
Correct :) you need to make a role exists in the DB first.

If you run `$ bin/console user:add:role` the role is created automatically if it doesnt exist yet. Or you can run `$ bin/console role:create` first.

Or programmatic, run `$bus->dispatch(new CreateRoleCommand(...))` first :)

**Comment by dedioweb** [comment] 2019-01-15 13:10
ok good
I created the role "client" with the command role: create 

but i have : UndefinedMethodException in src/Controller/User/RegisterController.php (line 39)
however, in the registerController it says that $userid is not initialized

it may be a simple thing that I forgot but I do not see

**Comment by ro0NL** [comment] 2019-01-15 13:15
you need to obtain the userId from the previously created user. Or generate a UUID upfront and use it in both `CreateUserCommand` as well as `AddUseRoleCommand`. This would be a bit more advanced/complex.

Now that i think of it,  the neatest way is to use an event subcriber.

Subscribing to `UserCreateEvent` will give you the created domain user entity, as such you can dispatch a new `AddUserRoleCommand` from there on, using `$event->user->getId()`.

Then a db role will always be created, wherever you dispatch `CreateUserCommand`.

**Comment by ro0NL** [comment] 2019-01-15 13:17
E.g. the demo app uses it to send a confirmation link for each created user: https://github.com/msgphp/symfony-demo-app/blob/master/src/EventSubscriber/SendRegistrationConfirmationUrl.php

Then, another subcriber will listen to `UserConfirmedEvent` and dispatches `EnableUserCommand`: https://github.com/msgphp/symfony-demo-app/blob/master/src/EventSubscriber/EnableConfirmedUser.php

This is how you create a flow of business logic using MsgPHP/message buses.

**Comment by dedioweb** [comment] 2019-01-15 13:51
Sorry, I can't see it clearly

**Comment by ro0NL** [comment] 2019-01-15 14:09
"Event subscribers" are regular message handlers: https://symfony.com/doc/current/messenger.html#registering-handlers

So in this case the handler would be something like:

```php
class AddRoleToCreatedUsed implements MessageHandlerInterface {
    private $commandBus;

    public function __construct(MessageBusInterface $commandBus) {
        $this->commandBus = $commandBus;
    }

    public  function __invoke(UserCreatedEvent $event) {
        $this->commandBus->dispatch(new AddUserRoleCommand($event->user->getId(), 'ROLE_IN_DB'));
    }
}
```

**Comment by dedioweb** [comment] 2019-01-15 15:07
So in src/EventUserCreate I created AddRoleToCreatedUser.php in which I put : 

`declare(strict_types=1);

namespace App\EventUserCreate;

use MsgPhp\User\Event\UserCreatedEvent;
use MsgPhp\User\Infra\Console\Command\AddUserRoleCommand;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;
use Symfony\Component\Messenger\MessageBusInterface;


class AddRoleToCreatedUser implements MessageHandlerInterface {
    private $commandBus;

    public function __construct(MessageBusInterface $commandBus) {
        $this->commandBus = $commandBus;
    }

    public  function __invoke(UserCreatedEvent $event) {
        dump($event);
        die();
        $this->commandBus->dispatch(new AddUserRoleCommand($event->user->getId(), 'client'));
    }
}`

when I do a `dump($event);
        die();`
he gets me the id
`AddRoleToCreatedUser.php on line 20:
UserCreatedEvent {#1015 ▼
  +user: User {#1010 ▼
    -id: UserId {#1103 ▼
      -id: "18"
    }
    -credential: EmailPassword {#1077 ▼
      -email: "test@dev.dev"
      -password: "$2y$13$n6hCmweMiiSkt/62GGXwsOC4eJiQdz7RC4VhPz1YlG9Ag1af0nfhS"
    }
    -passwordResetToken: null
    -passwordRequestedAt: null
    -roles: PersistentCollection {#1011 ▶}
  }
}`
but 
Argument 1 passed to MsgPhp\User\Infra\Console\Command\AddUserRoleCommand::__construct() must implement interface MsgPhp\Domain\Factory\EntityAwareFactoryInterface, instance of MsgPhp\User\UserId given, called in /Users/dedioweb/Sites/clients4/src/EventUserCreate/AddRoleToCreatedUser.php on line 21

We are almost there :-)

**Comment by ro0NL** [comment] 2019-01-15 15:15
in the demo app i've put all "event subcribers" (special type of message handlers) in `src/EventSubcriber`: see https://github.com/msgphp/symfony-demo-app/tree/master/src/EventSubscriber

Then using i register them all at once here: https://github.com/msgphp/symfony-demo-app/blob/master/config/services.yaml#L40

In your case, the `use` is wrong:

```
use MsgPhp\User\Infra\Console\Command\AddUserRoleCommand;
```

MsgPHP has "message commands" and "console commands", respectively in the namespaces:
- `MsgPhp\User\Command\`
- `MsgPhp\User\Infra\Console\Command\`

You should dispatch a message command here, not a console one.

**Comment by dedioweb** [comment] 2019-01-15 15:58
Enjoy, it's fixed :)
to respect a logic:
in src i created /EventSubscriber/AddRoleToCreatedUser.php
```
namespace App\EventSubscriber;

use MsgPhp\User\Command\AddUserRoleCommand;
use MsgPhp\User\Event\UserCreatedEvent;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;
use Symfony\Component\Messenger\MessageBusInterface;


class AddRoleToCreatedUser implements MessageHandlerInterface {
    private $commandBus;

    public function __construct(MessageBusInterface $commandBus) {
        $this->commandBus = $commandBus;
    }

    public  function __invoke(UserCreatedEvent $event) {

        $this->commandBus->dispatch(new AddUserRoleCommand($event->user->getId(), 'client'));
    }
}
```

thank you for your patience

**Comment by dedioweb** [comment] 2019-01-15 16:15
last little thing, if I want to display the role in the profile view, which variable to use?

**Comment by ro0NL** [comment] 2019-01-15 16:32
@dedioweb  a user can have many roles (zero, one or more).

To get the user role**s**:

option 1) ask the repository and assign directly to your template

````php
render('template.html.twig', ['user_roles' => $userRoleRepository->findAllByUserId($currentUser->getId())
```

The repository can be injected using the `MsgPhp\User\Repository\UserRoleRepositoryInterface` service ID.

The current user can be obtained using e.g. a param converter: https://github.com/msgphp/symfony-demo-app/blob/master/src/Controller/User/ProfileController.php#L36

option 2) enable the user inversed side: e.g. `User::getRoles()` by using our `RolesField`: https://github.com/msgphp/symfony-demo-app/blob/master/src/Entity/User/User.php#L36

Then in your template it's `{{ msgphp_user.current.roles }}`

**Comment by dedioweb** [comment] 2019-01-15 23:02
I tested the first option
Here is the dump(msgphp_user.current.roles)
```
DomainCollection {#1212 ▼
  -collection: PersistentCollection {#433 ▼
    -snapshot: []
    -owner: User {#475 ▼
      -id: UserId {#409 ▼
        -id: "6"
      }
      -credential: EmailPassword {#470 ▶}
      -passwordResetToken: "1e5237034224a633ff27aa61531cb8e20a590d434e304609c988bfb917c8c3a9"
      -passwordRequestedAt: DateTime @1547568006 {#471 ▶}
      -roles: PersistentCollection {#433}
    }
    -association: array:15 [ …15]
    -em: EntityManager {#403 …11}
    -backRefFieldName: "user"
    -typeClass: ClassMetadata {#430 …}
    -isDirty: false
    #collection: ArrayCollection {#497 ▶}
    #initialized: false
  }
}
```

**Comment by dedioweb** [comment] 2019-01-16 17:43
so, 
**My Entity/user/User.php** 
```
namespace App\Entity\User;

use Doctrine\ORM\Mapping as ORM;
use MsgPhp\Domain\Event\DomainEventHandlerInterface;
use MsgPhp\Domain\Event\DomainEventHandlerTrait;
use MsgPhp\User\Entity\Credential\EmailPassword;
use MsgPhp\User\Entity\Features\EmailPasswordCredential;
use MsgPhp\User\Entity\Features\ResettablePassword;
use MsgPhp\User\Entity\Fields\RolesField;
use MsgPhp\User\Entity\User as BaseUser;
use MsgPhp\User\UserIdInterface;

/**
 * @ORM\Entity()
 */
class User extends BaseUser implements DomainEventHandlerInterface
{
    use DomainEventHandlerTrait;
    use EmailPasswordCredential;
    use ResettablePassword;
    use RolesField;

    /** @ORM\Id() @ORM\GeneratedValue() @ORM\Column(type="msgphp_user_id", length=191) */
    private $id;

    public function __construct(UserIdInterface $id, string $email, string $password)
    {
        $this->id = $id;
        $this->credential = new EmailPassword($email, $password);
    }

    public function getId(): UserIdInterface
    {
        return $this->id;
    }
    
    
}
```
**My Entity/user/UserRole.php**
```
declare(strict_types=1);

namespace App\Entity\User;

use Doctrine\ORM\Mapping as ORM;
use MsgPhp\User\Entity\UserRole as BaseUserRole;

/**
 * @ORM\Entity()
 * @ORM\AssociationOverrides({
 *     @ORM\AssociationOverride(name="user", inversedBy="roles")
 * })
 *
 * @final
 */
class UserRole extends BaseUserRole
{
}
```
In template i use {{ msgphp_user.current.roles }}

Result : 
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class MsgPhp\Domain\Infra\Doctrine\DomainCollection could not be converted to string").

**Comment by ro0NL** [comment] 2019-01-16 18:18
> a user can have many roles (zero, one or more).

you get an instance of [`DomainCollectionInterface`](https://msgphp.github.io/docs/ddd/collections/), containing `UserRole` entities.

In twig you need to loop, instead of printing it.

have a look at the demo app: https://github.com/msgphp/symfony-demo-app/blob/master/templates/user/profile.html.twig#L30

forgot to mention, but by using `app.user.roles` in twig you get the roles from all configured `role_providers`, opposed to `msgphp_user.current.roles` which only holds the database assigned roles.

i suggest `composer require debug` in your project so you can use `{{ dump(variable) }}` in your templates ;) things probably work as exepcted. These are twig templating errors :)

**Comment by dedioweb** [comment] 2019-01-16 18:39
ok, the example given works, it refers me well the roles of the database, for against it me out 2 ?? the ROLE_USER and the name of the role I added in the role table of the database, I do not understand anymore

**Comment by ro0NL** [comment] 2019-01-16 18:48
>  it refers me well the roles of the database

so it works?

> for against it me out 2 ??

i dont understand this

looks like you're issues are now twig related: https://twig.symfony.com/doc/2.x/ (really checkout the mentioned dump() function to see your values)

for the conceptual difference between `app.user` and `msgphp_user.current` see https://stovepipe.systems/post/decoupling-your-security-user

i suggest to continue on symfony slack :) https://symfony-devs.slack.com/messages/C8RSYM3MF you can try either #msgphp or #support channel.

**Comment by dedioweb** [comment] 2019-01-16 19:00
Yes it works
{{ dump(app.user.roles) }}
```
array:2 [▼
  0 => "ROLE_USER"
  1 => "client"
]
```

**Comment by dedioweb** [comment] 2019-01-17 16:32
I managed to get the right result with
```{% if app.user.roles[1] == 'client' %}Vous êtes client {% else %} Administrateur{% endif %}```
:-)

**Comment by ro0NL** [comment] 2019-01-17 16:41
better use `{% if is_granted('ROLE_NAME') %}` in twig: https://symfony.com/doc/current/reference/twig_reference.html#is-granted :)

shall we close?

**Comment by dedioweb** [comment] 2019-01-17 16:53
yes 
A big thank-you

**Closed** 2019-01-17 16:53 UTC
Labels: support
