### ISSUE TITLE
1709 Index column size too large

### ISSUE THREAD

**Issue by thar0x29a** [msgphp/msgphp#140] opened 2018-04-18 08:41 UTC
As soon I try to get the schema in sync I get this error. 

```
2018-04-18T10:27:47+02:00 [error] Error thrown while running command "doctrine:schema:update --force". Message: "An exception occurred while executing 'CREATE TABLE role (name VARCHAR(255) NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':

SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes."

In AbstractMySQLDriver.php line 125:

  An exception occurred while executing 'CREATE TABLE role (name VARCHAR(255)
   NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4
  _unicode_ci ENGINE = InnoDB':

  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maxim
  um column size is 767 bytes.
```

Since I cant rlly change the size in your user bundle, I declare it as issue and would feel happy for any solution :/

Edit:
https://stackoverflow.com/questions/42043205/how-to-fix-mysql-index-column-size-too-large-laravel-migrate?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

This does the job. Change the default settings in my.ini and doctrine.yaml (or whatever you use)

**Comment by ro0NL** [comment] 2018-04-18 11:40
Hi @thar0x29a 

i'm assuming you refer to the default `Role` definition, the one created from the skeleton, i.e.: https://github.com/msgphp/msgphp/blob/master/src/UserBundle/Resources/skeleton/entity/Role.php#L22

> Since I cant rlly change the size in your user bundle, 

You can :) just modify the generated `Role` annotations...

AFAIK the issue is fixed as of mysql 5.7 so im not sure there's anything to do on our side =/ as mentioned you can change the size, switch to utf8 from utf8mb4... or upgrade :)

**Comment by ro0NL** [comment] 2018-04-22 08:29
@thar0x29a can you confirm the issue can be worked around by updating your annotation/mapping before updating the database schema?

**Comment by ro0NL** [comment] 2018-05-28 16:09
Closing as explained in https://github.com/msgphp/msgphp/issues/140#issuecomment-382357753

Feel free to re-open if necessary.

**Closed by ro0NL** 2018-05-28 16:09 UTC
Labels: user domain
